server {
    listen 80;
    server_name capstone.eterosoft.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name capstone.eterosoft.com;

    ssl_certificate     /etc/letsencrypt/live/capstone.eterosoft.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/capstone.eterosoft.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:js|css|svg|woff2?|ttf|eot|png|jpg|jpeg|gif|ico)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }
}
