"""Api request table

Revision ID: 2adb32c7594b
Revises: 4d00a51f1998
Create Date: 2026-08-31 15:35:48.664851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adb32c7594b'
down_revision: Union[str, Sequence[str], None] = '4d00a51f1998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('suspicious_count', sa.Integer(), nullable=False),
    sa.Column('benign_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_batches_user_id'), 'detection_batches', ['user_id'], unique=False)
    op.create_table('api_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.String(length=2048), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('attack_tag', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('response_status', sa.String(length=100), nullable=False),
    sa.Column('response_headers', sa.JSON(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('raw_request', sa.JSON(), nullable=False),
    sa.Column('request_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['detection_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_requests_batch_id'), 'api_requests', ['batch_id'], unique=False)
    op.create_index(op.f('ix_api_requests_created_at'), 'api_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_requests_endpoint'), 'api_requests', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_requests_user_id'), 'api_requests', ['user_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('prediction', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('attack_type', sa.String(length=80), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['api_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_detections_prediction'), 'detections', ['prediction'], unique=False)
    op.create_index(op.f('ix_detections_risk_level'), 'detections', ['risk_level'], unique=False)
    op.create_table('extracted_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('url_length', sa.Integer(), nullable=False),
    sa.Column('endpoint_depth', sa.Integer(), nullable=False),
    sa.Column('query_param_count', sa.Integer(), nullable=False),
    sa.Column('body_length', sa.Integer(), nullable=False),
    sa.Column('header_count', sa.Integer(), nullable=False),
    sa.Column('cookie_length', sa.Integer(), nullable=False),
    sa.Column('user_agent_length', sa.Integer(), nullable=False),
    sa.Column('special_char_count', sa.Integer(), nullable=False),
    sa.Column('special_char_density', sa.Float(), nullable=False),
    sa.Column('sql_pattern_score', sa.Float(), nullable=False),
    sa.Column('xss_pattern_score', sa.Float(), nullable=False),
    sa.Column('traversal_pattern_score', sa.Float(), nullable=False),
    sa.Column('command_pattern_score', sa.Float(), nullable=False),
    sa.Column('log_injection_pattern_score', sa.Float(), nullable=False),
    sa.Column('log4j_pattern_score', sa.Float(), nullable=False),
    sa.Column('cookie_injection_pattern_score', sa.Float(), nullable=False),
    sa.Column('composite_anomaly_score', sa.Float(), nullable=False),
    sa.Column('response_body_length', sa.Integer(), nullable=False),
    sa.Column('response_header_count', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('is_error_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['api_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_features')
    op.drop_index(op.f('ix_detections_risk_level'), table_name='detections')
    op.drop_index(op.f('ix_detections_prediction'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_api_requests_user_id'), table_name='api_requests')
    op.drop_index(op.f('ix_api_requests_endpoint'), table_name='api_requests')
    op.drop_index(op.f('ix_api_requests_created_at'), table_name='api_requests')
    op.drop_index(op.f('ix_api_requests_batch_id'), table_name='api_requests')
    op.drop_table('api_requests')
    op.drop_index(op.f('ix_detection_batches_user_id'), table_name='detection_batches')
    op.drop_table('detection_batches')
    # ### end Alembic commands ###
